api_instance: "18546441"
environment: "Development"
http:
    process:
        request:
            basePath: "dev/papi/geny-accounts-registrations/v1"
            process_client_secret: ""
            process_client_id: ""
    request:
        host: "non-prod.api.local.eu.henryschein.com"
reconnection:
    freq: "1000"
    attempts: "5"
